services:
  ssl-vision-client:
    image: robocupssl/ssl-vision-client:2.1.0@sha256:2694ba31a1f5d99460b283d03b0f650d4a6317774bfe175a61deb0a12753ee5d
    command: [ "-address", ":8082" ]
    network_mode: host
    restart: on-failure

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.18.0@sha256:8994ff7dea015ab052662516eff23c8aea8394521deece9190343829f51f9357
    command: [ "-address", ":8083" ]
    network_mode: host
    restart: on-failure

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:3.20.3@sha256:d62d772de063c2951f600a0b7898803f97822f4f46a412a731e42f7d82a99dc7
    command: [ "-address", "localhost:8081" ]
    network_mode: host
    restart: on-failure
    volumes:
      - "./data/ssl-game-controller:/config:rw"

  ssl-auto-recorder:
    image: robocupssl/ssl-auto-recorder:1.11.0@sha256:8bbcaca7924f947b4e61083f4b50c8f2029ee7adf3f8a8f73c1503eb4749f330
    command: [ "-http-port", "8084" ]
    network_mode: host
    restart: on-failure
    volumes:
      - "./data/ssl-auto-recorder:/data:rw"

  autoref-tigers:
    image: tigersmannheim/auto-referee-vnc:1.7.1@sha256:6f859943a4735cb29d8307e6ede3dbe79074eb2fcb11472b08cfaff7d7b2f4c8
    command: [ "-a", "-hl" ]
    network_mode: host
    restart: on-failure
    profiles:
      - autorefs-headless

  autoref-erforce:
    image: roboticserlangen/autoref:commit-6f15f574ea80@sha256:3d7c5933c12eb193a1fefcfd6aba86fba42875c588cc883dc20d0bfcb66b11cb
    command: [ ]
    network_mode: host
    restart: on-failure
    profiles:
      - autorefs-headless

  autoref-ui-tigers:
    image: tigersmannheim/auto-referee-vnc:1.7.1@sha256:6f859943a4735cb29d8307e6ede3dbe79074eb2fcb11472b08cfaff7d7b2f4c8
    command: [ "-a" ]
    environment:
      - DISPLAY=${DISPLAY:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    restart: on-failure
    profiles:
      - autorefs-ui

  autoref-ui-erforce:
    image: roboticserlangen/autoref:commit-6f15f574ea80@sha256:3d7c5933c12eb193a1fefcfd6aba86fba42875c588cc883dc20d0bfcb66b11cb
    command: [ "gui" ]
    environment:
      - DISPLAY=${DISPLAY:-}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    restart: on-failure
    profiles:
      - autorefs-ui
